# Generated by Django 5.2.1 on 2025-06-26 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('noOfReplays', models.IntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2, null=True)),
                ('genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='listing.genre')),
            ],
        ),
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replay', models.BooleanField(default=False)),
                ('timeSpentPlaying', models.DurationField(null=True)),
                ('startDate', models.DateField(null=True)),
                ('completedDate', models.DateField(null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listing.game')),
            ],
        ),
    ]
