# Generated by Django 5.2.1 on 2025-06-09 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Plays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replay', models.BooleanField(default=False)),
                ('timeSpentPlaying', models.DurationField(null=True)),
                ('startDate', models.DateField(null=True)),
                ('completedDate', models.DateField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='games',
            name='timeSpentPlaying',
        ),
        migrations.AddField(
            model_name='games',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True),
        ),
    ]
