# Generated by Django 5.2.1 on 2025-07-17 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_game_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
