# Generated by Django 5.2.1 on 2025-06-09 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_genres_plays_remove_games_timespentplaying_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plays',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='listing.games'),
        ),
    ]
