# Generated by Django 5.2.1 on 2025-06-15 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0003_plays_game'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Games',
            new_name='Game',
        ),
        migrations.RenameModel(
            old_name='Genres',
            new_name='Genre',
        ),
        migrations.RenameModel(
            old_name='Plays',
            new_name='Play',
        ),
    ]
