# Generated by Django 5.2.1 on 2025-06-18 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0004_rename_games_game_rename_genres_genre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='id',
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
