# Generated by Django 5.2.1 on 2025-05-14 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simapple', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='greetings',
            old_name='firstname',
            new_name='firstgreet',
        ),
        migrations.RenameField(
            model_name='greetings',
            old_name='lastname',
            new_name='secondgreet',
        ),
        migrations.AddField(
            model_name='greetings',
            name='count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='greetings',
            name='language',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
