# Generated by Django 5.2.1 on 2025-05-19 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simapple', '0002_rename_firstname_greetings_firstgreet_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, null=True)),
                ('phone', models.IntegerField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Greetings',
        ),
    ]
